import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Enterprise } from '../models/enterprise.model';

@Injectable({
  providedIn: 'root',
})
export class EnterpriseService {
  private enterprises: Enterprise[] = [
    //Zaya Brava
    {
      id: 'zaya-brava',
      nome: 'Zaya Brava',
      descricao: 'O Zaya Brava By Construttore',
      endereco: 'Praia Brava - Itajaí',
      enderecoTotal:
        'R. Delfim Mário de Pádua Peixoto, 1513-1685 - Praia Brava, Itajaí - SC, 88306-806',
      fachada: '../assets/img/enterprises/zaya-brava/zaya.jpg',
      banner: '../assets/img/enterprises/zaya-brava/zaya.jpg',
      googleMapsLink: 'https://goo.gl/maps/iXuY6D9FmugmX37f6',
      sobre: [
        'Zaya carrega algo como “a ilusão”, “a fantasia”, ou “a que tem a força criativa”. Portanto, o nome Zaya está associado à diversas simbologias, que vão desde elementos da natureza até características de uma pessoa iluminada, positiva e com o dote da criatividade.',
      ],
      diferenciais: ['Em breve mais informações!'],
      oEmpreendimento: [
        'Academia',
        'Piscina aquecida',
        'Solarium',
        'Salão de festas Gourmet',
        'Sala de jogos',
        'Espaço kids',
      ],
      oApartamento: [
        'Piso em porcelanato 100x100 cm',
        'Teto rebaixado em gesso acartonado',
        'Lavabo',
        'Sacada panorâmica com churrasqueira à carvão',
        'Sistema de água aquecida a gás',
        'Instalação para ar condicionado tipo SPLIT',
        'Hidrômetro individual',
      ],
      aObra: [
        { nome: 'Projeto e Planejamento', porcentagem: '50' },
        { nome: 'Fundação', porcentagem: '10' },
        { nome: 'Estruturas', porcentagem: '0' },
        { nome: 'Paredes', porcentagem: '0' },
        { nome: 'Acabamentos', porcentagem: '0' },
        { nome: 'Instalações', porcentagem: '0' },
      ],
      imagensObra: [''],
      status: 'PRÉ-LANÇAMENTO',
      imagens: [
        '../assets/img/enterprises/brava-dreams/fachada-01.webp',
        '../assets/img/enterprises/brava-dreams/fachada-02.webp',
        '../assets/img/enterprises/brava-dreams/fachada-03.webp',
        '../assets/img/enterprises/brava-dreams/fachada-04.webp',
        '../assets/img/enterprises/brava-dreams/living.webp',
        '../assets/img/enterprises/brava-dreams/piscina.webp',
        '../assets/img/enterprises/brava-dreams/piscina-02.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_01.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_02.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_03.webp',
      ],
      plantas: [],
      mapa: '',
    },
    //Brava Dreams
    {
      id: 'brava-dreams',
      nome: 'Brava Dreams',
      descricao: 'O Brava Dreams',
      endereco: 'Praia Brava - Itajaí, SC',
      fachada: '../assets/img/enterprises/brava-dreams/fachada-04.webp',
      banner: '../assets/img/enterprises/brava-dreams/fachada-04.webp',
      enderecoTotal:
        'Av. Carlos Drummond de Andrade, 33 - Santa Clara, Itajaí - SC, 88306-830',
      googleMapsLink: 'https://goo.gl/maps/yCphrxnNjeyXhQvLA',
      sobre: [
        'Um empreendimento para sonhar e viver. Esse é o Brava Dreams, o novo lançamento da Construttore Empreendimentos que chega para elevar o conceito de moradia frente mar e alto padrão na Praia Brava em Itajaí.',
        'Apartamentos com área privativa de até 361 m², piscina exclusiva por unidade e vista panorâmica, unem-se à excelente localização, formando a combinação perfeita entre exclusividade, você e a Praia Brava.',
      ],
      diferenciais: [
        'Arquitetura inspirada em Dubai com fachada tecnológica, estilo moderno, conforto e design. Torre única com exclusivos apartamentos e vista incomparável para o mar. Localização privilegiada – na beira mar da Brava Sul, altíssimo padrão de acabamento.',
      ],
      oEmpreendimento: [
        'Apartamentos com plantas diferenciadas, sendo alguns duplex',
        'Espaço Festas e Gourmet',
        'Piscina aquecida',
        'Terraço Lounge',
        'Fitness',
        'Solarium',
        'Ponto de abastecimento elétrico para carros',
      ],
      oApartamento: [
        '3 ou 4 suítes',
        'Vista panorâmica para o mar',
        'Fechadura biométrica',
        'Sacada com Churrasqueira a Carvão',
        'Piscina aquecida em cada apartamento',
        'Living integrado com cozinha',
        'Lavabo',
        'Área de Serviço',
        'Sacada técnica',
        'Banheiros com piso aquecido e ponto para toalheiro elétrico',
        'Revestimento cerâmico nas paredes dos banheiros e áreas de serviço',
        'Rebaixamento de gesso em todos os ambientes',
        'Isolamento térmico e acústico',
        'Infraestrutura para ar condicionado VRF com cassetes 1 via',
        'Infraestrutura para aspiração central',
        'Infraestrutura para automação de iluminação, áudio e vídeo, climatização, cortineiros e piscina',
        'Infraestrutura para aquecedor e anel de recirculação de água quente',
        'Medidor de água individual',
      ],
      aObra: [
        { nome: 'Projeto e Planejamento', porcentagem: '100' },
        { nome: 'Fundação', porcentagem: '100' },
        { nome: 'Estruturas', porcentagem: '70' },
        { nome: 'Paredes', porcentagem: '30' },
        { nome: 'Acabamentos', porcentagem: '0' },
        { nome: 'Instalações', porcentagem: '0' },
      ],
      imagensObra: [''],
      status: 'LANÇAMENTO',
      imagens: [
        '../assets/img/enterprises/brava-dreams/fachada-01.webp',
        '../assets/img/enterprises/brava-dreams/fachada-02.webp',
        '../assets/img/enterprises/brava-dreams/fachada-03.webp',
        '../assets/img/enterprises/brava-dreams/fachada-04.webp',
        '../assets/img/enterprises/brava-dreams/living.webp',
        '../assets/img/enterprises/brava-dreams/piscina.webp',
        '../assets/img/enterprises/brava-dreams/piscina-02.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_01.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_02.webp',
        '../assets/img/enterprises/brava-dreams/plantas/p_03.webp',
      ],
      plantas: [],
      mapa: '',
    },
    //Brava View
    {
      id: 'brava-view',
      nome: 'Brava View',
      descricao: 'O Brava View',
      endereco: 'Praia Brava, Itajaí',
      enderecoTotal: 'R. Aririba, 71 - Praia Brava, Itajaí - SC, 88306-780',
      googleMapsLink: 'https://goo.gl/maps/wGzLs4qRqfrAFqBx5',
      fachada: '../assets/img/enterprises/brava-view/brava_view.webp',
      banner: '../assets/img/enterprises/brava-view/brava_view.webp',
      sobre: [
        'A Praia Brava é hoje uma das regiões com maior índice de valorização do Litoral Catarinense. Localizada entre Itajaí e Balneário Camboriú, o Brava View é o empreendimento perfeito para quem quer morar bem, em contato direto com a natureza e infra estrutura voltada ao lazer e segurança.',
        'Uma alternativa para quem busca por qualidade de vida próximo à uma das mais badaladas praias da região com diferenciais que permitem transformar projetos de vida em realizações pessoais.',
      ],
      diferenciais: [
        'Para quem busca uma vida mais próxima da natureza, sem perder o contato com seu lado urbano, o Brava View é a escolha perfeita. Localizado entre Itajaí e Balneário Camboriú o empreendimento conta com excelente potencial de valorização no presente e no futuro.',
      ],
      oEmpreendimento: [
        'Academia',
        'Playground',
        'Piscina adulto e infantil',
        'Salão de festas Gourmet',
        'Área de terraço',
      ],
      oApartamento: [
        '01 Suíte + 01 ou 02 Dormitórios',
        'Sala de jantar com piso em porcelanato',
        'Cozinha e área de serviço em porcelanato',
        'Sala de estar com piso em porcelanato',
        'Dormitórios com piso de vinílico',
        'Banheiro social com piso cerâmico',
        'Detalhes em gesso',
        'Sacada com churrasqueira à carvão',
        'Sistema de água aquecida a gás',
        'Instalação para ar condicionado tipo SPLIT',
        'Hidrômetro individual',
      ],
      aObra: [
        { nome: 'Projeto e Planejamento', porcentagem: '100' },
        { nome: 'Fundação', porcentagem: '100' },
        { nome: 'Estruturas', porcentagem: '100' },
        { nome: 'Paredes', porcentagem: '100' },
        { nome: 'Acabamentos', porcentagem: '100' },
        { nome: 'Instalações', porcentagem: '100' },
      ],
      imagensObra: [''],
      status: 'ENTREGUE : 2021',
      imagens: [
        '../assets/img/enterprises/brava-view/launch-01.webp',
        '../assets/img/enterprises/brava-view/launch-02.webp',
        './assets/img/enterprises/brava-view/launch-03.webp',
      ],
      plantas: [],
      mapa: '',
    },
    //Solares da Brava
    {
      id: 'solares-da-brava',
      nome: 'Solares da Brava',
      descricao: 'O Solares da Brava',
      endereco: 'Praia Brava, Itajaí',
      enderecoTotal:
        'Av. Carlos Drummond de Andrade, 200 - Praia Brava, Itajaí - SC, 88306-806',
      googleMapsLink: 'https://goo.gl/maps/EuE2iSYsiQPAJ5LU7',
      fachada: '../assets/img/enterprises/solares/solares.webp',
      banner: '../assets/img/enterprises/solares/solares.webp',
      sobre: [
        'Da harmonização do que há de mais belo na natureza, aliado à luxuosa concepção arquitetônica, acaba de nascer uma nova forma de viver.',
        'Num lugar irradiante, onde a vitalidade contagia constantemente a todos, surge o novo lar da sua vida. Conheça o que é viver bem, em um espaço que inspira e intensifica as experiências do seu dia-a-dia.',
      ],
      diferenciais: [
        'Harmonizando a luxuosa concepção arquitetônica com o que há de mais belo na natureza o Solares da Brava tem o conforto que você merece.',
      ],
      oEmpreendimento: [
        'Salão de Festas Gourmet',
        'Home Cinema',
        'Brinquedoteca',
        'Fitness Center',
        'Sala de Jogos',
        'Piscina',
        'Playground',
        'Lounge | Garage Band',
        'Solarium',
        'Sauna',
        '',
      ],
      oApartamento: [
        'Amplos Ambientes',
        'Apartamentos de 3 suítes',
        'Cozinha Gourmet',
        'Churrasqueira à carvão',
        'Estendal',
        'Área de serviço',
        'Banheiro de serviço',
        'Área técnica para Split',
        'Sala de jantar e Living',
        'Lavabo',
        'Piso em Porcelanato de alto padrão',
        'Piso vinílico nos dormitórios',
        'Tubulação para split',
        'Pontos p/ automação de persianas',
        'Tubulação para aspiração central',
        'Tubulação para estrutura de áudio',
        'Garage box',
        '02 ou 03 vagas de garagem',
      ],
      aObra: [
        { nome: 'Projeto e Planejamento', porcentagem: '100' },
        { nome: 'Fundação', porcentagem: '100' },
        { nome: 'Estruturas', porcentagem: '100' },
        { nome: 'Paredes', porcentagem: '100' },
        { nome: 'Acabamentos', porcentagem: '100' },
        { nome: 'Instalações', porcentagem: '100' },
      ],
      imagensObra: [''],
      status: 'ENTREGUE : 2021',
      imagens: [
        '../assets/img/enterprises/solares/fachada_01.webp',
        '../assets/img/enterprises/solares/fachada_02.webp',
        '../assets/img/enterprises/solares/fachada_03.webp',
        //'../assets/img/enterprises/solares/hall_01.webp',
        '../assets/img/enterprises/solares/hall_02.webp',
        '../assets/img/enterprises/solares/salao_01.webp',
        '../assets/img/enterprises/solares/salao_02.webp',
        '../assets/img/enterprises/solares/sala_jogos.webp',
        '../assets/img/enterprises/solares/brinquedoteca.webp',
        '../assets/img/enterprises/solares/cinema.webp',
        '../assets/img/enterprises/solares/academia.webp',
        '../assets/img/enterprises/solares/solares.webp',
        '../assets/img/enterprises/solares/plantas/p_01.webp',
      ],
      plantas: [],
      mapa: '',
    },
    //Privilège Brava
    {
      id: 'privilege-brava',
      nome: 'Privilège Brava',
      descricao: 'O Privilège Brava',
      endereco: 'Praia Brava, Itajaí',
      enderecoTotal:
        'R. Vergínia Ângelo Severino, 59 - Praia Brava, Itajaí - SC, 88306-837',
      googleMapsLink: 'https://goo.gl/maps/Umo1hPBCG5BtTtxQA',
      fachada: '../assets/img/enterprises/privilege/privilege.webp',
      banner: '../assets/img/enterprises/privilege/privilege.webp',
      sobre: [
        'Um empreendimento completo, localizado a poucos metros do mar e cercado de verde, com vista privilegiada. Com sua arquitetura moderna e uma área de lazer completa, venha desfrutar desta joia rara localizada em uma das mais belas praias do sul do Brasil.',
      ],
      diferenciais: [
        'Quem busca mais que um empreendimento quer qualidade de vida, buscando conforto e mobilidade.',
        'Todas as áreas de lazer do Privilège Brava foram minuciosamente projetadas para você, seus familiares e amigos terem a melhor experiência.',
      ],
      oEmpreendimento: [
        'Academia',
        'Espaço Kids',
        'Piscina Kids',
        'Prainha',
        'Piscina adulto com raia',
        'Salão de festas Gourmet',
        'Sala de jogos',
        'Espaço churrasco',
      ],
      oApartamento: [
        '01 Suíte + 02 Demi-suítes',
        'Piso em porcelanato 80x80 cm',
        'Rebaixamento em gesso nos banheiros, lavabo e área de serviço',
        'Sacada Grill com churrasqueira à carvão',
        'Sistema de água aquecida a gás',
        'Instalação para ar condicionado tipo SPLIT',
        'Hidrômetro individual',
      ],
      aObra: [
        { nome: 'Projeto e Planejamento', porcentagem: '100' },
        { nome: 'Fundação', porcentagem: '100' },
        { nome: 'Estruturas', porcentagem: '100' },
        { nome: 'Paredes', porcentagem: '100' },
        { nome: 'Acabamentos', porcentagem: '100' },
        { nome: 'Instalações', porcentagem: '100' },
      ],
      imagensObra: [''],
      status: 'ENTREGUE : 2021',
      imagens: [
        '../assets/img/enterprises/brava-view/launch-01.webp',
        '../assets/img/enterprises/brava-view/launch-02.webp',
        './assets/img/enterprises/brava-view/launch-03.webp',
      ],
      plantas: [],
      mapa: '',
    },
  ];

  constructor() {}

  getEnterprises(): Observable<Enterprise[]> {
    return of(this.enterprises);
  }

  getEnterpriseById(id: string): Observable<Enterprise | undefined> {
    const enterprise = this.enterprises.find((e) => e.id === id);
    return of(enterprise);
  }
}
